user = {
    '_id': 0,
    "email": '',
    "timestamp": 0,
    "operando": False,
    "tipo_conta": "treino",
    "valor": 2,
    "minimo": 0,
    "goal": 100,
    "soros": False,
    "percent_soros": 0,
    "stoploss": 20,
    "percent_martin": 0,
    "max_gale": 2,
    "tipo_martin": "seguro",
    "tipo_gale": "martin",
    "tendencia": False,
    "tipo_tendencia": "velas",
    "periodo_tendencia": 21,
    "desvio_tendencia": 0.1,
    "tipo_par": "auto",
    "delay": False,
    "correcao": 1,
    "tempo": 5,
    "tipo_lista":"propria",
    "lista": [],
    "plano": "comum"
}