User = {
    "id": None,
    "adm": False,
    "email": '',
    "timestamp": 0,
    "operando": False,
    "aprovado": False,
    "tipo_conta": "treino",
    "valor": 2,
    "minimo": 0,
    "goal": 100,
    "soros": False,
    "percent_soros": 0,
    "stoploss": 20,
    "martin": True,
    "percent_martin": 0,
    "max_gale": 2,
    "tipo_gale": "seguro",
}