user = {
    '_id': 0,
    "email": '',
    "lista": [],
    "timestamp": 0,
    "porcentagem": False,
    "num_lista": "1",
    "plano": "teste",
    "operando": False,
    "tipo_lista":"Da casa",

    "tipo_conta": "treino",
    "tipo_par": "auto",
    "stoploss": 20,
    "stopwin": 10,
    "valor": 2,
    "tempo": 5,
    
    "minimo": 0,
    "correcao": 1,
    "delay": False,
    "tipo_stop": "movel",   
    
    "tipo_gale": "martingale",
    "tipo_martin": "simples",
    "tipo_soros": "normal", 
    "vez_gale": "vela",
    "gale_pct": 100,
    "prestoploss": False,
    "prestopwin": 0,
    "scalper_loss": 0,        
    "scalper_win": 0,      

    "max_gale": 2,
    "max_soros": 1,
    "ciclos_gale": [],        
    "ciclos_soros": [],       
    
    "noticias_pre": 0,
    "noticias_pos": 0,
    "toros": 0,               

    "autogale": 2,            
    "autotime": 1,    
    "poshit": 0,
    "posgale": "Nenhum",
    "max_trades": 10,
    "estrategia": "MHI",      
    "paridade": "EURUSD",   
    
    "auto": False,           
    "autocycles": 0, 
    "hits": 1, 
    "assert": 0, 
    "catalogador": "old", 

    "periodo_tendencia": 21,
    "tendencia": False,

    "taxas_vela": "atual",
    "no_posgale": False,
}